name: Build .NET Framework Desktop App

on:
  workflow_call:
    inputs:
      solution:
        required: true
        type: string

    outputs:
      output-path:
        description: "Build output path"
        value: ${{ jobs.build.outputs.output-path }}

env:
  SOLUTION_FILE: SA.sln

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3

      - name: Restore NuGet packages
        run: nuget restore $env:SOLUTION_FILE

      - name: Build with MSBuild
        run: msbuild $env:SOLUTION_FILE /p:Configuration=Release
