name: Release .NET Framework Desktop App

on:
  workflow_call:
    inputs:
      solution:
        required: true
        type: string

    outputs:
      output-path:
        description: "Build output path"
        value: ${{ jobs.release.outputs.output-path }}

env:
  SOLUTION_FILE: SA.sln

jobs:
  release:
    runs-on: windows-2022

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: output

      - name: Zip Build Output
        run: |
          $Tag = "${{ github.ref_name }}"
          $ZipName = "SubtitlesAdjuster_$Tag.zip"
          powershell Compress-Archive -Path output\*.exe -DestinationPath $ZipName

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Subtitles Adjuster ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: SubtitlesAdjuster_${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
